// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Process = require("process");
var Puppeteer = require("puppeteer");

function $$default() {
  return Puppeteer.launch(undefined).then((function (browser) {
                return browser.newPage().then((function (page) {
                                  var options = {
                                    timeout: 20000,
                                    waitUntil: "load"
                                  };
                                  return page.goto("https://lux.poswallet.io", options).then((function () {
                                                          var partial_arg = ( function (element) { return element.setAttribute("novalidate", true); } );
                                                          return page.$eval("#kc-form-login", Curry.__1(partial_arg));
                                                        })).then((function () {
                                                        return page.type("#username", process.env.EMAIL, undefined);
                                                      })).then((function () {
                                                      return page.type("#password", process.env.PASSWORD, undefined);
                                                    })).then((function () {
                                                    return page.click("#kc-login", undefined);
                                                  })).then((function () {
                                                  return page.waitForSelector("body > div.page-wrapper > div > div > div:nth-child(2) > div > div > div.ibox-body > div.d-flex.justify-content-between.m-b-20 > div > h3", undefined);
                                                })).then((function () {
                                                console.log("screenshotting");
                                                var options = {
                                                  path: "./screenshot.png"
                                                };
                                                return page.screenshot(options);
                                              }));
                                })).then((function () {
                                return browser.close();
                              })).then((function () {
                              return Promise.resolve((Process.exit(0), /* () */0));
                            }));
              }));
}

$$default(/* () */0);

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/*  Not a pure module */
