// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Process = require("process");
var Puppeteer = require("puppeteer");

function $$default() {
  return Puppeteer.launch(undefined).then((function (browser) {
                return browser.newPage().then((function (page) {
                                  return page.goto("https://lux.poswallet.io", undefined).then((function () {
                                                console.log("screenshotting");
                                                var options = {
                                                  path: "./screenshot.png"
                                                };
                                                return page.screenshot(options);
                                              }));
                                })).then((function () {
                                return browser.close();
                              })).then((function () {
                              return Promise.resolve((Process.exit(0), /* () */0));
                            }));
              }));
}

$$default(/* () */0);

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/*  Not a pure module */
